apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssql-persistent-volume
spec:
  storageClassName: "pstore-high"
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/sqldata"