apiVersion: v1
kind: Service
metadata:
  name: user-service-nodeport
spec:
  type: NodePort
  selector:
    app: user-service
  ports:
    - name: user-service
      protocol: TCP
      port: 7093
      targetPort: 7093